language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3.5"

stages:
  - test
  - analysis

install:
  - pip install -r tests/requirements.txt
script:
  - pytest -v

jobs:
  include:
    - stage: analysis
      install:
        - pip install -r tests/requirements.txt
        - pip install pytype
      script:
        - pytype --python-version $TRAVIS_PYTHON_VERSION
