language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3.5"

jobs:
  include:
    - stage: "Tests"

      name: "Unit tests"
      install:
        - pip install -r tests/requirements.txt
      script:
        - pytest -v

      name: "Static analysis"
      install:
        - pip install -r tests/requirements.txt
        - pip install pytype
      script:
        - pytype --python-version $TRAVIS_PYTHON_VERSION
